import datetime

FEATURE_SHAPE = (3, 17, 17)
BATCH_SIZE = 128
INPUT_DIMS = (BATCH_SIZE, *FEATURE_SHAPE)
MODEL_NAME = "AGENT_TASK1"
SAVE_PATH = f"./{MODEL_NAME}-"
LOAD_PATH = ""
ACTIONS = ['UP', 'RIGHT', 'DOWN', 'LEFT', 'WAIT']
INITIAL_EXPLORE_PROB = 1
MINIMAL_EXPLORE_PROB = 0.01
EXPLORE_DECAY = 2000
TRANSITION_MEM_SIZE = 100_000
RECORD_ENEMY_TRANSITIONS = 1  # TODO only store enemy transitions if enemy has better score
GAMMA = 0.99
MINIMAL_TRANSITION_LEN = 10_000
UPDATE_TARGET_STEPS = 10_000
